# GoReleaser configuration for port-selector
# https://goreleaser.com

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy

builds:
  - id: port-selector
    main: ./cmd/port-selector
    binary: port-selector

    env:
      # Disable CGO for static binaries and macOS compatibility
      - CGO_ENABLED=0

    ldflags:
      # Embed version from git tag
      - -s -w -X main.version={{.Version}}

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    # Skip unsupported combinations
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    format: binary

    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs(\(.+\))?:'
      - '^test(\(.+\))?:'
      - '^chore(\(.+\))?:'
      - '^refactor(\(.+\))?:'
      - '(?i)typo'
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Documentation Updates'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Other Changes'
      order: 999

brews:
  - name: port-selector
    repository:
      owner: dapi
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/dapi/port-selector"
    description: "Port allocator for parallel local dev environments"
    license: "MIT"
    install: |
      binary_name = if OS.mac?
        Hardware::CPU.arm? ? "port-selector-darwin-arm64" : "port-selector-darwin-amd64"
      else
        Hardware::CPU.arm? ? "port-selector-linux-arm64" : "port-selector-linux-amd64"
      end
      bin.install binary_name => "port-selector"
    test: |
      system "#{bin}/port-selector", "--help"

release:
  github:
    owner: dapi
    name: port-selector

  # Generate release notes from CHANGELOG.md
  prerelease: auto

  # Keep latest releases
  mode: append

  # Release notes footer
  footer: |
    ## Installation

    ### macOS (Apple Silicon)
    ```bash
    curl -L -o port-selector https://github.com/dapi/port-selector/releases/download/{{ .Tag }}/port-selector_{{ .Version }}_darwin_arm64
    chmod +x port-selector
    sudo mv port-selector /usr/local/bin/
    ```

    ### macOS (Intel)
    ```bash
    curl -L -o port-selector https://github.com/dapi/port-selector/releases/download/{{ .Tag }}/port-selector_{{ .Version }}_darwin_amd64
    chmod +x port-selector
    sudo mv port-selector /usr/local/bin/
    ```

    ### Linux (amd64)
    ```bash
    curl -L -o port-selector https://github.com/dapi/port-selector/releases/download/{{ .Tag }}/port-selector_{{ .Version }}_linux_amd64
    chmod +x port-selector
    sudo mv port-selector /usr/local/bin/
    ```

    ### Windows
    Download `port-selector_{{ .Version }}_windows_amd64.exe` from the assets below and add to PATH.

    **Full Changelog**: https://github.com/dapi/port-selector/compare/{{ .PreviousTag }}...{{ .Tag }}
